-- Create the database
CREATE DATABASE sequelized_burgers;
USE sequelized_burgers;

-- Create the table
CREATE TABLE burgers
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
burger_name VARCHAR(150) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);